CREATE TABLE product_sku (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    size VARCHAR(10),
    customization_id BIGINT,
    patch BOOLEAN NOT NULL DEFAULT FALSE,
    sponsorship BOOLEAN NOT NULL DEFAULT FALSE,
    sku VARCHAR(50) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    -- Foreign key constraints
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (customization_id) REFERENCES customization(id)
);