CREATE TABLE supplier (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    responsible VARCHAR(255),
    identification VARCHAR(20),
    phone VARCHAR(20),
    foto TEXT
);

INSERT INTO
    SUPPLIER (name, responsible, identification, phone, foto)
VALUES
    (
        'Fornecedor A',
        'João Silva',
        '123456789',
        '+55 11 1234-5678',
        'http://example.com/foto1.jpg'
    ),
    (
        'Fornecedor B',
        'Maria Oliveira',
        '987654321',
        '+55 21 9876-5432',
        'http://example.com/foto2.jpg'
    ),
    (
        'Fornecedor C',
        'Carlos Pereira',
        '456789123',
        '+55 31 4567-8912',
        'http://example.com/foto3.jpg'
    );