CREATE TABLE supply_item (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_sku_id INT NOT NULL,
    supply_id INT NOT NULL,
    quantity INT NOT NULL,
    defect BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_product_sku
        FOREIGN KEY (product_sku_id) 
        REFERENCES product_sku(id),
    CONSTRAINT fk_supply
        FOREIGN KEY (supply_id)
        REFERENCES supply(id)
);
